"use strict";

/**
 * Limited liquid-US scan universe. This is NOT the full market.
 * Used when Alpaca's movers screener is unavailable, and as the Market page catalog.
 */
const SCAN_UNIVERSE = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "NVDA", name: "NVIDIA" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "GOOGL", name: "Alphabet A" },
  { symbol: "GOOG", name: "Alphabet C" },
  { symbol: "META", name: "Meta" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "BRK.B", name: "Berkshire B" },
  { symbol: "JPM", name: "JPMorgan" },
  { symbol: "V", name: "Visa" },
  { symbol: "UNH", name: "UnitedHealth" },
  { symbol: "XOM", name: "Exxon Mobil" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "LLY", name: "Eli Lilly" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "COST", name: "Costco" },
  { symbol: "ABBV", name: "AbbVie" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "AMD", name: "AMD" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "TMO", name: "Thermo Fisher" },
  { symbol: "ADBE", name: "Adobe" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "GE", name: "GE" },
  { symbol: "CAT", name: "Caterpillar" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "INTU", name: "Intuit" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "BKNG", name: "Booking" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "MU", name: "Micron" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "SPGI", name: "S&P Global" },
  { symbol: "PFE", name: "Pfizer" },
  { symbol: "T", name: "AT&T" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "CMCSA", name: "Comcast" },
  { symbol: "NKE", name: "Nike" },
  { symbol: "BA", name: "Boeing" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "GILD", name: "Gilead" },
  { symbol: "MDLZ", name: "Mondelez" },
  { symbol: "ADP", name: "ADP" },
  { symbol: "C", name: "Citigroup" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "SCHW", name: "Charles Schwab" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "SQ", name: "Block" },
  { symbol: "SHOP", name: "Shopify" },
  { symbol: "SPOT", name: "Spotify" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "HOOD", name: "Robinhood" },
  { symbol: "PLTR", name: "Palantir" },
  { symbol: "SNOW", name: "Snowflake" },
  { symbol: "CRWD", name: "CrowdStrike" },
  { symbol: "PANW", name: "Palo Alto" },
  { symbol: "DDOG", name: "Datadog" },
  { symbol: "NET", name: "Cloudflare" },
  { symbol: "ZS", name: "Zscaler" },
  { symbol: "SMCI", name: "Super Micro" },
  { symbol: "ARM", name: "Arm" },
  { symbol: "TSM", name: "TSMC" },
  { symbol: "ASML", name: "ASML" },
  { symbol: "BABA", name: "Alibaba" },
  { symbol: "NIO", name: "NIO" },
  { symbol: "RIVN", name: "Rivian" },
  { symbol: "LCID", name: "Lucid" },
  { symbol: "F", name: "Ford" },
  { symbol: "GM", name: "GM" },
  { symbol: "RCL", name: "Royal Caribbean" },
  { symbol: "MAR", name: "Marriott" },
  { symbol: "DAL", name: "Delta" },
  { symbol: "UAL", name: "United Airlines" },
  { symbol: "AAL", name: "American Airlines" },
  { symbol: "CCL", name: "Carnival" },
  { symbol: "MGM", name: "MGM" },
  { symbol: "DKNG", name: "DraftKings" },
  { symbol: "PENN", name: "PENN Entertainment" },
  { symbol: "GME", name: "GameStop" },
  { symbol: "AMC", name: "AMC" },
  { symbol: "BB", name: "BlackBerry" },
  { symbol: "SOFI", name: "SoFi" },
  { symbol: "AFRM", name: "Affirm" },
  { symbol: "UPST", name: "Upstart" },
  { symbol: "SNAP", name: "Snap" },
  { symbol: "PINS", name: "Pinterest" },
  { symbol: "RDDT", name: "Reddit" },
  { symbol: "U", name: "Unity" },
  { symbol: "RBLX", name: "Roblox" },
  { symbol: "TTD", name: "Trade Desk" },
  { symbol: "ROKU", name: "Roku" },
  { symbol: "ZM", name: "Zoom" },
  { symbol: "DOCU", name: "DocuSign" },
  { symbol: "OKTA", name: "Okta" },
  { symbol: "MDB", name: "MongoDB" },
  { symbol: "TEAM", name: "Atlassian" },
  { symbol: "WDAY", name: "Workday" },
  { symbol: "S", name: "SentinelOne" },
  { symbol: "PATH", name: "UiPath" },
  { symbol: "AI", name: "C3.ai" },
  { symbol: "BBAI", name: "BigBear.ai" },
  { symbol: "SOUN", name: "SoundHound" },
  { symbol: "IONQ", name: "IonQ" },
  { symbol: "RGTI", name: "Rigetti" },
  { symbol: "QBTS", name: "D-Wave" },
  { symbol: "MARA", name: "MARA Holdings" },
  { symbol: "RIOT", name: "Riot Platforms" },
  { symbol: "CLSK", name: "CleanSpark" },
  { symbol: "MSTR", name: "MicroStrategy" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "CVNA", name: "Carvana" },
  { symbol: "W", name: "Wayfair" },
  { symbol: "CHWY", name: "Chewy" },
  { symbol: "PTON", name: "Peloton" },
  { symbol: "BYND", name: "Beyond Meat" },
  { symbol: "MRNA", name: "Moderna" },
  { symbol: "BNTX", name: "BioNTech" },
  { symbol: "NVAX", name: "Novavax" },
  { symbol: "CRSP", name: "CRISPR" },
  { symbol: "DNA", name: "Ginkgo Bioworks" },
  { symbol: "OPEN", name: "Opendoor" },
  { symbol: "UWMC", name: "UWM" },
  { symbol: "XPEV", name: "XPeng" },
  { symbol: "LI", name: "Li Auto" },
  { symbol: "JD", name: "JD.com" },
  { symbol: "PDD", name: "PDD Holdings" },
  { symbol: "NU", name: "Nu Holdings" },
  { symbol: "MELI", name: "MercadoLibre" },
  { symbol: "SE", name: "Sea Limited" },
  { symbol: "GOLD", name: "Barrick" },
  { symbol: "NEM", name: "Newmont" },
  { symbol: "FCX", name: "Freeport" },
  { symbol: "AA", name: "Alcoa" },
  { symbol: "CLF", name: "Cleveland-Cliffs" },
  { symbol: "X", name: "U.S. Steel" },
  { symbol: "VALE", name: "Vale" },
  { symbol: "BTU", name: "Peabody" },
  { symbol: "DVN", name: "Devon Energy" },
  { symbol: "OXY", name: "Occidental" },
  { symbol: "CVX", name: "Chevron" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "SLB", name: "Schlumberger" },
  { symbol: "HAL", name: "Halliburton" },
  { symbol: "MPC", name: "Marathon Petroleum" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "APA", name: "APA Corp" },
  { symbol: "FSLR", name: "First Solar" },
  { symbol: "ENPH", name: "Enphase" },
  { symbol: "SEDG", name: "SolarEdge" },
  { symbol: "RUN", name: "Sunrun" },
  { symbol: "PLUG", name: "Plug Power" },
  { symbol: "CHPT", name: "ChargePoint" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "DELL", name: "Dell" },
  { symbol: "HPQ", name: "HP" },
  { symbol: "HPE", name: "HPE" },
  { symbol: "NTAP", name: "NetApp" },
  { symbol: "STX", name: "Seagate" },
  { symbol: "WDC", name: "Western Digital" },
  { symbol: "SNDK", name: "Sandisk" },
  { symbol: "MRVL", name: "Marvell" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "SWKS", name: "Skyworks" },
  { symbol: "QRVO", name: "Qorvo" },
  { symbol: "KLAC", name: "KLA" },
  { symbol: "SNPS", name: "Synopsys" },
  { symbol: "CDNS", name: "Cadence" },
  { symbol: "ANET", name: "Arista" },
  { symbol: "DECK", name: "Deckers" },
  { symbol: "LULU", name: "Lululemon" },
  { symbol: "TGT", name: "Target" },
  { symbol: "LOW", name: "Lowe's" },
  { symbol: "DG", name: "Dollar General" },
  { symbol: "DLTR", name: "Dollar Tree" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "TJX", name: "TJX" },
  { symbol: "CMG", name: "Chipotle" },
  { symbol: "MCD", name: "McDonald's" },
  { symbol: "YUM", name: "Yum" },
  { symbol: "DPZ", name: "Domino's" },
  { symbol: "WING", name: "Wingstop" },
  { symbol: "CAVA", name: "CAVA" },
  { symbol: "BROS", name: "Dutch Bros" },
  { symbol: "CELH", name: "Celsius" },
  { symbol: "MNST", name: "Monster" },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
];

function uniqueUniverse() {
  const seen = new Set();
  const out = [];
  for (const row of SCAN_UNIVERSE) {
    const symbol = String(row.symbol || "").toUpperCase();
    if (!symbol || seen.has(symbol)) continue;
    seen.add(symbol);
    out.push({ symbol, name: row.name || symbol });
  }
  return out;
}

const UNIVERSE = uniqueUniverse();
const NAME_BY_SYMBOL = Object.fromEntries(UNIVERSE.map((r) => [r.symbol, r.name]));

function lookupName(symbol) {
  const s = String(symbol || "").toUpperCase();
  return NAME_BY_SYMBOL[s] || s;
}

function coverageMeta() {
  return {
    type: "limited_provider_universe",
    size: UNIVERSE.length,
    fullMarket: false,
    label: `Limited universe (${UNIVERSE.length} liquid U.S. symbols)`,
    description:
      "VoltScan does not scan every listed U.S. stock. Gainers, volume, and volatility lists are ranked inside this cached liquid universe, plus any symbols on your watchlist. Alpaca movers/most-actives are used when the plan allows, and are still not guaranteed to be the entire market.",
  };
}

module.exports = {
  UNIVERSE,
  NAME_BY_SYMBOL,
  lookupName,
  coverageMeta,
};
